[tox]
envlist = py311, py312, py313, pypy3, doctest

[testenv]
commands = attest attest.tests []

[testenv:doctest]
deps = sphinx
changedir = docs
commands = sphinx-build -WEab {envname} -d {envtmpdir}/doctrees .  {envtmpdir}/{envname}

[testenv:html]
deps = sphinx
changedir = docs
commands = sphinx-build -WEab {envname} -d {envtmpdir}/doctrees .  {envtmpdir}/{envname}

[testenv:linkcheck]
deps = sphinx
changedir = docs
commands = sphinx-build -WEab {envname} -d {envtmpdir}/doctrees .  {envtmpdir}/{envname}

[testenv:spelling]
deps =
    sphinx
    sphinxcontrib-spelling>=1.0
    pyenchant
changedir = docs
commands = sphinx-build -Eab {envname} -d {envtmpdir}/doctrees .  {envtmpdir}/{envname}
